### ISSUE TITLE
Consider adding notebook to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [onichandame/notebook#27]
Hey @onichandame, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by onichandame** [comment]
@billy1624 Thx for your excellent work on SeaORM! This project is purely created for my own practice so it may be removed/renamed/... at any time in the future.
However I have created another [SeaORM-related library](https://github.com/onichandame/crud-rs/) which will be published for everyone. Once that library is complete I will definitely post it to the showcase board

**Comment by billy1624** [comment]
Sure! Take your time!! @onichandame
